name: test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

env:
  GO_VERSION: '^1.19'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -  -b $(go env GOPATH)/bin v1.49.0
      - run: echo "PATH=$PATH:/home/runner/go/bin" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.0